# Generated by Django 4.2 on 2025-12-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='resources.bizmachine', verbose_name='机器')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='resources.bizproduct', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.appuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': '交易流水',
                'verbose_name_plural': '交易流水',
                'db_table': 'log_transaction',
            },
        ),
        migrations.CreateModel(
            name='LogRestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='补货数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='补货时间')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='resources.bizmachine', verbose_name='机器')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='resources.bizproduct', verbose_name='商品')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='users.sysstaff', verbose_name='运维人员')),
            ],
            options={
                'verbose_name': '补货记录',
                'verbose_name_plural': '补货记录',
                'db_table': 'log_restock',
            },
        ),
        migrations.CreateModel(
            name='BizInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0, verbose_name='当前库存')),
                ('max_capacity', models.IntegerField(default=20, verbose_name='最大容量')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='resources.bizmachine', verbose_name='机器')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='resources.bizproduct', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'biz_inventory',
                'unique_together': {('machine', 'product')},
            },
        ),
    ]
