# Generated by Django 6.0 on 2025-12-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_create_triggers'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrestock',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总成本'),
        ),
        migrations.AddField(
            model_name='logrestock',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单位成本'),
        ),
        migrations.AddField(
            model_name='logtransaction',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本价'),
        ),
    ]
