# Generated by Django 6.0 on 2025-12-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_logrestock_total_cost_logrestock_unit_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logrestock',
            name='total_cost',
        ),
    ]
