# Generated by Django 4.2 on 2025-12-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', '缺货'), ('fault', '故障')], default='low_stock', max_length=20, verbose_name='类型')),
                ('message', models.CharField(max_length=500, verbose_name='报警内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报警时间')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='resources.bizmachine', verbose_name='机器')),
            ],
            options={
                'verbose_name': '报警日志',
                'verbose_name_plural': '报警日志',
                'db_table': 'log_alert',
            },
        ),
        migrations.CreateModel(
            name='StatDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总营收')),
                ('order_count', models.IntegerField(default=0, verbose_name='订单数')),
                ('alert_count', models.IntegerField(default=0, verbose_name='报警次数')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='resources.bizmachine', verbose_name='机器')),
            ],
            options={
                'verbose_name': '日结统计',
                'verbose_name_plural': '日结统计',
                'db_table': 'stat_daily',
                'unique_together': {('date', 'machine')},
            },
        ),
    ]
