# Generated by Django 6.0 on 2025-12-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statdaily',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总成本'),
        ),
        migrations.AddField(
            model_name='statdaily',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总利润'),
        ),
    ]
