# Generated by Django 6.0 on 2025-12-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_statdaily_total_cost_statdaily_total_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statdaily',
            name='total_profit',
        ),
    ]
