# Generated by Django 4.2 on 2025-12-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BizMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_code', models.CharField(max_length=50, unique=True, verbose_name='机器编号')),
                ('location', models.CharField(max_length=200, verbose_name='位置')),
                ('status', models.CharField(choices=[('normal', '正常'), ('fault', '故障')], default='normal', max_length=20, verbose_name='状态')),
                ('region_code', models.CharField(max_length=20, verbose_name='所属区域')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '贩卖机',
                'verbose_name_plural': '贩卖机',
                'db_table': 'biz_machine',
            },
        ),
        migrations.CreateModel(
            name='BizSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('contact', models.CharField(max_length=100, verbose_name='联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'biz_supplier',
            },
        ),
        migrations.CreateModel(
            name='BizProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='进价')),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='售价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='resources.bizsupplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'biz_product',
            },
        ),
    ]
